theme: jekyll-theme-tactile
site_name: "Winter School on Neurobotics in ONPU (2018) | Computer Vision subsection"
title: "Winter School | ONPU | 2018"
author: "Nikita Kovalenko"
description: "Winter School on Neurobotics | Computer Vision subsection"
